### ISSUE TITLE
How to get the index_a and index_b in config file?

### ISSUE THREAD

**Issue by uujianghhh** [Yzmblog/MonoHuman#13]
Hi,I noticed that you have different index_a and index_b in each config files from different datasets,I wonder  how do you get the specific index_a and index_b?

**Comment by staymylove** [comment]
Oh, yes. I also want to run the 'people_snapshot_public' dataset on Monohuman code. But I have no idea how to prepare the data.

**Comment by Yzmblog** [comment]
Hi, please refer to the script in tools/prepare_wild/select_keyframe.py.
