### ISSUE TITLE
Question about observation bank

### ISSUE THREAD

**Issue by MooreManor** [Yzmblog/MonoHuman#14]
@Yzmblog 

Hello! MonoHuman is excellent work.

I have a question about the implementation of the observation bank. From the [code snippet](https://github.com/Yzmblog/MonoHuman/blob/6429fdbf8c3eb7f8f77326a969e6519e91dad6cc/core/data/monohuman/monodata.py#L152-L156), I find you use manually predefined two frames of index a and b as front and back. In section 3.3 of your paper, you said, "Then, we find the k pairs with the closest pose from these two sets." In my opinion, MonoHuman should match all poses in the videos and then compare the texture map's completeness in the k pairs, which seems different from the implementation in the code.

Do I misunderstand something? Besides, can you offer the script to choose the keyframe (i.e. index_a and index_b)?

**Comment by Yzmblog** [comment]
Hi, for the zju_mocap dataset, we select the pairs offline and put the results in config files. For the in-the-wild data, please refer to the script in tools/prepare_wild/select_keyframe.py. As the codes of the texture map matching are missing and too complicated to recap, it simply uses the first stage to pick the keyframes in the script.
