### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by chunjins** [Yzmblog/MonoHuman#15]
Hi @Yzmblog, 

Thanks for the excellent work. It would be one of the most important baselines for our project.

I have some questions about the data you use to evaluate the novel view and novel pose synthesis. For the novel pose evaluation, from section C of the supplemental materials, you mentioned that you sample frames from all cameras at the rate of 30 in Set B and the number of picked frames is 184. I am a bit confused about this part. 

Taking 393 which is the longest sequence as an example, 
N_setB = 658 * 0.2 = 131.6, 
N_sample = N_setB * 23 / 30 =  100.9
Then how could you get 184 frames for evaluation? 

Kindly do let me know how could I get the same frames you use to calculate the scores of Table A2 and A3.

Thanks again!

**Comment by Yzmblog** [comment]
Hi, I think you are right and I have miscalculated the frame number. To get the same frames, here is the process I used: 1. Divide the camera frames as: nv_eval_frames = all_frames[:-len(all_frames)//5]; np_eval_frames = all_frames[-len(all_frames)//5:]; 
2. Then sample at a rate of 30: nv_eval_frames = nv_eval_frames[::30]; np_eval_frames = np_eval_frames[::30].

The above is the code I used to divide them, So I think your calculation is correct. Thanks for pointing it out, I will update it.

**Comment by TShoreWind** [comment]
@chunjins Hello, I have been working on the Monohuman project recently. I noticed that you have successfully evaluated the indicators of Monohuman. I would like to ask if you could provide the correct training and evaluation methods. This is very important to me. I am really looking forward to your reply.

![Image](https://github.com/user-attachments/assets/e4940024-b334-4333-b5c8-95bcb299bf84)

**Comment by chunjins** [comment]
Hi @TShoreWind, for me, I strictly followed the author's instructions and the default setting to train and evaluate the results. 
1. Divide the camera frames as: nv_eval_frames = all_frames[:-len(all_frames)//5]; np_eval_frames = all_frames[-len(all_frames)//5:];
2. Then sample at a rate of 30: nv_eval_frames = nv_eval_frames[::30]; np_eval_frames = np_eval_frames[::30].

**Comment by TShoreWind** [comment]
Could you please send me a copy of the specific process document? My email address is 869944574@qq.com. @chunjins Thank you very much.

**Comment by chunjins** [comment]
I think you can follow the author's data processing script directly, as I did not apply any custom or additional processing.

**Comment by TShoreWind** [comment]
评估出来的指标不对，pose指标又是如何评估呢？ @Yzmblog @chunjins

**Comment by TShoreWind** [comment]
The evaluated indicators are incorrect. How is the pose indicator evaluated then? @chunjins @Yzmblog

**Comment by TShoreWind** [comment]
I carefully followed the author's method for classification, but the result was still very poor.

![Image](https://github.com/user-attachments/assets/780ee731-ef0b-46dd-a139-328b4c058c95)

![Image](https://github.com/user-attachments/assets/db809176-bfc7-484c-9e85-acb9c3ffc094) @Yzmblog @chunjins
