### ISSUE TITLE
请教关于人体运动差异

### ISSUE THREAD

**Issue by mystijk** [Yzmblog/MonoHuman#2]
不同人是有不同的运动差异的，在传统渲染管线里，可以通过对人设定不同的绑定参数来实现，在这里怎么才能实现这个差异？

**Comment by Yzmblog** [comment]
> 不同人是有不同的运动差异的，在传统渲染管线里，可以通过对人设定不同的绑定参数来实现，在这里怎么才能实现这个差异？

Hi. 对的，每个人会有不同的运动差异。在这里我们的模型是case specific的，也就是每个人会单独训练一个模型，对每个人设定不同的绑定参数就相当于我们这里对于每个人的模型会学习到不一样的deformation参数。
