### ISSUE TITLE
About videos in the wild

### ISSUE THREAD

**Issue by xyIsHere** [Yzmblog/MonoHuman#4]
Dear authors,

Could you show a specific example of the preprocessing for the videos in the wild, e.g., how to generate accurate human mask and how to get the camera matrix? 
I saw in the paper, you mentioned that RVM is used for mask generation. However, the mask we obtained values between 0 and 1. Is a hard mask required for this task or we can just used the matting results?

Thanks

**Comment by Yzmblog** [comment]
> Dear authors,
> 
> Could you show a specific example of the preprocessing for the videos in the wild, e.g., how to generate accurate human mask and how to get the camera matrix? I saw in the paper, you mentioned that RVM is used for mask generation. However, the mask we obtained values between 0 and 1. Is a hard mask required for this task or we can just used the matting results?
> 
> Thanks

Hi, We need a hard mask, so you can use a threshold to filter the estimated results. And we get the camera matrix estimated by PARE. I will update some in-the-wild examples later, thanks for your feedback sincerely! :)

**Comment by Dipankar1997161** [comment]
> > Dear authors,
> > Could you show a specific example of the preprocessing for the videos in the wild, e.g., how to generate accurate human mask and how to get the camera matrix? I saw in the paper, you mentioned that RVM is used for mask generation. However, the mask we obtained values between 0 and 1. Is a hard mask required for this task or we can just used the matting results?
> > Thanks
> 
> Hi, We need a hard mask, so you can use a threshold to filter the estimated results. And we get the camera matrix estimated by PARE. I will update some in-the-wild examples later, thanks for your feedback sincerely! :)

@Yzmblog,
Hello, 

I got the smpl values from PARE,
however, what about the camera intrinsic and extrinsic values in this case? Since PARE gives weak perspective cameras. 

I found out 2 cases that the weak perspective cameras can be used as follows but which one is correct?
E = [[s, 0, 0, tx],
 [0, s, 0, ty]
[ 0, 0, 1, 0], 
[0, 0, 0, 1 ]]

another - [[ 1.   0.   0.   tx]
 [ 0.   1.   0.  ty]
 [ 0.   0.   1.   s]
 [ 0.   0.   0.   1. ]]
 
 
Could you provide information on how can I construct the cam params so I can process my file further for training

**Comment by Yzmblog** [comment]
> > > Dear authors,
> > > Could you show a specific example of the preprocessing for the videos in the wild, e.g., how to generate accurate human mask and how to get the camera matrix? I saw in the paper, you mentioned that RVM is used for mask generation. However, the mask we obtained values between 0 and 1. Is a hard mask required for this task or we can just used the matting results?
> > > Thanks
> > 
> > 
> > Hi, We need a hard mask, so you can use a threshold to filter the estimated results. And we get the camera matrix estimated by PARE. I will update some in-the-wild examples later, thanks for your feedback sincerely! :)
> 
> @Yzmblog, Hello,
> 
> I got the smpl values from PARE, however, what about the camera intrinsic and extrinsic values in this case? Since PARE gives weak perspective cameras.
> 
> I found out 2 cases that the weak perspective cameras can be used as follows but which one is correct? E = [[s, 0, 0, tx], [0, s, 0, ty] [ 0, 0, 1, 0], [0, 0, 0, 1 ]]
> 
> another - [[ 1. 0. 0. tx] [ 0. 1. 0. ty] [ 0. 0. 1. s] [ 0. 0. 0. 1. ]]
> 
> Could you provide information on how can I construct the cam params so I can process my file further for training

Hi, you should first convert (s, tx, ty) to (tx, ty, tz), and then the second format is right.
