### ISSUE TITLE
Error in the Evaluation Code

### ISSUE THREAD

**Issue by seunguk-do** [Yzmblog/MonoHuman#5]
Hi, thank you for sharing great work.

It seems like the function run_eval in run.py does not run. The error occurs in the line 247 since the ray_mask is 1-dim tensor and the pred_img_norm is 2-dim tensor. And also, from the renderig result maked by ray_img, the SSIM and LPIPS cannot be evaluated. Can you tell me how did you exactly evaluate the renderings?

**Comment by Yzmblog** [comment]
> Hi, thank you for sharing great work.
> 
> It seems like the function run_eval in run.py does not run. The error occurs in the line 247 since the ray_mask is 1-dim tensor and the pred_img_norm is 2-dim tensor. And also, from the renderig result maked by ray_img, the SSIM and LPIPS cannot be evaluated. Can you tell me how did you exactly evaluate the renderings?

Hi, Thanks for your feedback! It's a bug in my code, we evaluate the whole image, so the ray_mask is unnecessary. Just deleting the ‘[ray_mask]’ will fix it. And I also update the code, Sorry for not checking that. Thanks again!

**Comment by seunguk-do** [comment]
Thank you!

**Comment by TShoreWind** [comment]
如何评估代码呢

**Comment by TShoreWind** [comment]
How do you evaluate the code

**Comment by TShoreWind** [comment]
@seunguk-do Hello, I want to know how to evaluate this model, and I would like to consult the specific process, which is very important to me. I have been studying this topic, and I am looking forward to your reply, which will be greatly appreciated.
