### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by muses0229** [Yzmblog/MonoHuman#6]

**Comment by yejr0229** [comment]
Below is a detailed error report.

Traceback (most recent call last):
  File "train.py", line 39, in <module>
    main()
  File "train.py", line 33, in main
    train_dataloader=train_loader)
  File "core/train/trainers/monohuman/trainer.py", line 177, in train
    net_output = self.network(**data)
  File "/home/yejr/miniconda3/envs/Monohuman/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "core/nets/monohuman/network.py", line 609, in forward
    all_ret = self._batchify_rays(packed_ray_infos, **kwargs)
  File "core/nets/monohuman/network.py", line 273, in _batchify_rays
    ret = self._render_rays(rays_flat[i:i+cfg.chunk], **kwargs)
  File "core/nets/monohuman/network.py", line 502, in _render_rays
    T_joints=canonical_joints)
  File "core/nets/monohuman/network.py", line 201, in _query_mlp
    rgb_feat=rgb_feat)
  File "core/nets/monohuman/network.py", line 236, in _apply_mlp_kernals
    dis, _ = closest_distance_to_points(T_joints, SMPL_PARENT, xyz)
  File "core/nets/monohuman/network.py", line 81, in closest_distance_to_points
    p_index = parent[min_index]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by Yzmblog** [comment]
> Below is a detailed error report.
> 
> Traceback (most recent call last): File "train.py", line 39, in main() File "train.py", line 33, in main train_dataloader=train_loader) File "core/train/trainers/monohuman/trainer.py", line 177, in train net_output = self.network(**data) File "/home/yejr/miniconda3/envs/Monohuman/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "core/nets/monohuman/network.py", line 609, in forward all_ret = self._batchify_rays(packed_ray_infos, **kwargs) File "core/nets/monohuman/network.py", line 273, in _batchify_rays ret = self._render_rays(rays_flat[i:i+cfg.chunk], **kwargs) File "core/nets/monohuman/network.py", line 502, in _render_rays T_joints=canonical_joints) File "core/nets/monohuman/network.py", line 201, in _query_mlp rgb_feat=rgb_feat) File "core/nets/monohuman/network.py", line 236, in _apply_mlp_kernals dis, _ = closest_distance_to_points(T_joints, SMPL_PARENT, xyz) File "core/nets/monohuman/network.py", line 81, in closest_distance_to_points p_index = parent[min_index] RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

Hi, I didn't encounter this error. Please check if you have modified any code. And It seems that the 'min_index' in GPU course the error. Just put 'min_index' to CPU will fix it.

**Comment by yejr0229** [comment]
> s

The problem has been solved, thank you
May I also ask if Monohuman can train together with multiple GPUs?

**Comment by yejr0229** [comment]
The problem has been solved, thank you
May I also ask if Monohuman can train together with multiple GPUs?

**Comment by Yzmblog** [comment]
> The problem has been solved, thank you May I also ask if Monohuman can train together with multiple GPUs?

It did not support DDP training yet. I will update it later. Thanks.
