### ISSUE TITLE
How much memory of GPU is needed for training?

### ISSUE THREAD

**Issue by garrisonz** [Yzmblog/MonoHuman#8]
I train Monohuman on a single 16G P100, but it fail with error "cuda out of memory".
May I know how much memory of GPU is needed when training. thanks

**Comment by garrisonz** [comment]
around 30G. 32G v100 is good enough.

**Comment by Yzmblog** [comment]
> I train Monohuman on a single 16G P100, but it fail with error "cuda out of memory". May I know how much memory of GPU is needed when training. thanks

Hi, if your CUDA memory is not enough, you can reduce the N_patches and size configs and increase sample_subject_ratio configs in https://github.com/Yzmblog/MonoHuman/blob/main/configs/default.yaml#LL132C1-L135C40 to fit your machine.
